"""Hermetic tests for tools/generate_classname_map_report.py (run via Bazel py_test)."""

from __future__ import annotations

import importlib.util
import os
import sys
import tempfile
from pathlib import Path
import unittest


def _load_generator_module():
    rd = os.environ.get("RUNFILES_DIR")
    if rd:
        for p in Path(rd).rglob("generate_classname_map_report.py"):
            if p.parent.name == "tools" and p.is_file():
                spec = importlib.util.spec_from_file_location("generate_classname_map_report", p)
                mod = importlib.util.module_from_spec(spec)
                assert spec.loader
                spec.loader.exec_module(mod)
                return mod
    # Workspace execution (e.g. python tests/map_generator/...)
    root = Path(__file__).resolve().parents[2]
    p = root / "tools" / "generate_classname_map_report.py"
    spec = importlib.util.spec_from_file_location("generate_classname_map_report", p)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader
    spec.loader.exec_module(mod)
    return mod


g = _load_generator_module()
sys.modules["generate_classname_map_report"] = g


def _find_runfile(filename: str) -> Path:
    rd = os.environ.get("RUNFILES_DIR")
    if rd:
        for p in Path(rd).rglob(filename):
            if p.is_file():
                return p
    # Local execution from workspace
    here = Path(__file__).resolve()
    for base in [here.parents[2], here.parents[1] / "fixtures"]:
        p = base / "fixtures" / filename if "fixtures" not in str(base) else base / filename
        if p.name != filename:
            p = base / "tests" / "fixtures" / filename
        if p.is_file():
            return p
    raise FileNotFoundError(f"Could not find {filename}")


class TestMapGenerator(unittest.TestCase):
    def test_parse_last_wins_duplicate_item_name(self) -> None:
        fixture = _find_runfile("items_map_generator_sample.xml")
        m = g.parse_items_crafting_groups(fixture)
        self.assertEqual(m["dupItem"], "Bows")
        self.assertEqual(len(m), 4)

    def test_generated_xml_ordering(self) -> None:
        fixture = _find_runfile("items_map_generator_sample.xml")
        items_map = g.parse_items_crafting_groups(fixture)
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "out.xml"
            g.write_generated_map_xml(
                items_map,
                out,
                source_label="items_map_generator_sample.xml",
            )
            text = out.read_text(encoding="utf-8")
        lines = [
            ln
            for ln in text.splitlines()
            if not ln.strip().startswith("<!-- items.xml input:")
            and not ln.strip().startswith("<!-- progression.xml:")
        ]
        normalized = "\n".join(lines) + "\n"
        expected = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_classname_map_report.py. Merge into ClassNameToCraftingSkillMap.xml; verify progressionMatchName in-game. requiredLevelOverride is never auto-generated. -->
<ClassNameToCraftingSkillMap>
  <!-- Bows -->
  <Item className="dupItem" craftingSkillGroup="Bows"/>
  <Item className="gunBowT0PrimitiveBow" craftingSkillGroup="Bows"/>
  <Item className="gunBowT1WoodenBow" craftingSkillGroup="Bows"/>

  <!-- Medical -->
  <Item className="medicalFirstAidBandage" craftingSkillGroup="Medical"/>
</ClassNameToCraftingSkillMap>
"""
        self.assertEqual(normalized, expected)

    def test_xml_escape_attr(self) -> None:
        self.assertEqual(g.xml_escape_attr('a"b&c'), "a&quot;b&amp;c")

    def test_suggest_iron_garage_transform_from_progression_xml(self) -> None:
        prog = _find_runfile("progression_map_generator_sample.xml")
        idx = g.parse_progression_unlock_index(prog)
        pm, status, _ = g.suggest_progression_match_name(
            "ironGarageDoor_FixtureTail", "Electrician", idx
        )
        self.assertEqual(status, "transform_xml")
        self.assertEqual(pm, "ironGarageDoor01_FixtureTail")

    def test_generated_xml_includes_progression_match_when_progression_passed(self) -> None:
        items = _find_runfile("items_map_generator_sample.xml")
        prog = _find_runfile("progression_map_generator_sample.xml")
        idx = g.parse_progression_unlock_index(prog)
        gen_map = {"ironGarageDoor_FixtureTail": "Electrician"}
        suggested, _ = g.compute_progression_matches_for_map(gen_map, idx)
        self.assertEqual(
            suggested.get("ironGarageDoor_FixtureTail"), "ironGarageDoor01_FixtureTail"
        )
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "out.xml"
            g.write_generated_map_xml(
                gen_map,
                out,
                source_label="items.xml",
                progression_match_by_class=suggested,
                progression_basename="progression_map_generator_sample.xml",
            )
            text = out.read_text(encoding="utf-8")
        self.assertIn('progressionMatchName="ironGarageDoor01_FixtureTail"', text)


if __name__ == "__main__":
    unittest.main()
